export const FETCH_RECOMMENDATIONS_START = 'FETCH_RECOMMENDATIONS_START';
export const FETCH_RECOMMENDATIONS_END = 'FETCH_RECOMMENDATIONS_END';
export const SEND_DATA_START = 'SEND_DATA_START';
export const SEND_DATA_END = 'SEND_DATA_END';
export const REQUEST_ERROR = 'REQUEST_ERROR';
